language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - secure: mnIFAdSbJrD7uRd58rNQ9gfRubrs4uKCOdqO1AVXsVq+EYr1CCPrBpkooP3QIzyP/LwFNNH3yzLovWhBb20nyovASIEBarCGHiLihMb2001XvgQEM7LkB6KhKiy2xiUWjmnKoo4YX8xpwSCQZfnlrX1XL1eqcZT15N9tar+sICKkkL8j53Fk0msnN+JrlJC2iUrzZ5C3HC1YbHlrDgvqdLeRQ8KKBkchhWf+TPJX6vh+zIlmvy19yqXaEcYbpBpqeG9VdYy4W0wBTmoxTnbzEatxL+kbm/pDvldlvp/bj6qmSBdUBvv2VDi2mfc9L5IJRFeapBv3QtU9xhMdr5QBk9xIHfup8t7naapqylSayMxzZCdP/i0eh3bA00IdUecPc0PnvbZvty648L/2AkFHTlAZhG+eto4qwWXptli3pApOqUD92y2BAavHnjyDLS6pzWTiHOtK2pCDXWVALmV2LPiIgoRDkrl6Qs+fjy48GT7U6K2SmV9OmUIMndfE+IH4oASe7X35jSPw63iSmh2VCZGGHPxNo9EgDxKWS3duiIWZWA4tTXb6ike+EpWA6j26PbeCJdfwLV/oanT25SWU4IMVoGLaLMdOgoQFA4s1LVrUg8q4FTiNSQQMkb5IVuR3kMdqZDaWMnMLDeGAeyDdMjKMlVxUSiyV1Wrye9qA5Bs=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
services:
- postgresql
after_success: npm run coverage
