language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - secure: mnIFAdSbJrD7uRd58rNQ9gfRubrs4uKCOdqO1AVXsVq+EYr1CCPrBpkooP3QIzyP/LwFNNH3yzLovWhBb20nyovASIEBarCGHiLihMb2001XvgQEM7LkB6KhKiy2xiUWjmnKoo4YX8xpwSCQZfnlrX1XL1eqcZT15N9tar+sICKkkL8j53Fk0msnN+JrlJC2iUrzZ5C3HC1YbHlrDgvqdLeRQ8KKBkchhWf+TPJX6vh+zIlmvy19yqXaEcYbpBpqeG9VdYy4W0wBTmoxTnbzEatxL+kbm/pDvldlvp/bj6qmSBdUBvv2VDi2mfc9L5IJRFeapBv3QtU9xhMdr5QBk9xIHfup8t7naapqylSayMxzZCdP/i0eh3bA00IdUecPc0PnvbZvty648L/2AkFHTlAZhG+eto4qwWXptli3pApOqUD92y2BAavHnjyDLS6pzWTiHOtK2pCDXWVALmV2LPiIgoRDkrl6Qs+fjy48GT7U6K2SmV9OmUIMndfE+IH4oASe7X35jSPw63iSmh2VCZGGHPxNo9EgDxKWS3duiIWZWA4tTXb6ike+EpWA6j26PbeCJdfwLV/oanT25SWU4IMVoGLaLMdOgoQFA4s1LVrUg8q4FTiNSQQMkb5IVuR3kMdqZDaWMnMLDeGAeyDdMjKMlVxUSiyV1Wrye9qA5Bs=
  - secure: aEt5xZoD+odHBpqJVsMEF7NJKw82VhdswAThwvBZHsaPWvzmr+1/6PcsqZOwzWgDxW+MDzLmAfevR6byF6e2atjO8Im937Ye7BEqATYn8hXmrezpjQ9dXRHLnS9l3WTZnTIFQ1NEAFe0S/gb33AItUeGdCf10ZrAsQNjLGKXVOlIyQ6NuZO72u1iJ1VqnN1wv17d7IdCf0rmWuG03cZlIOLdBI1DyVbsy9EoQwibVXb3F/K0ez0yuGfVMU/mKJ5+Drxu2F/z2ywXpT2RNPyO/cDyRI8jJwDw6dz0cCZgJg62koJ/T/IytI+PPcgsu9AaSzzJoQXXvJ6Om9oVI6dRCT0zIAT4jaLVHG64dV9oG1aLeCaJcbBTJXE5/HbB2JjqE1+wG5UjZwKuwwbT7elWsQj5egS6KHymT8ZpvTI7JglkSTJU7h3dl1hUpCVSZUF2vLlovTtQEkYmzByUehcyC/KDOe5uG+9gFvqGbLqr6qn1ZCL+sO4PWvSxHYP8bpGzPGOlAggFW9EaE5j97WwLIOi7lNhN8S+DrTqMOCBTFRfTLUhxoGkCTPSD333MSFLNcKmvjhXf2p0KIK1izq1SzIGI6RIzRFC2v5lr9uPmRM9PzAgtVf7l1t8cO2XzSokdZrDIv6kj7a8LYPhmGNLDjbU+mHVel1pB8bdDwvx32dk=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
services:
- postgresql
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: MLHrvFA35U6CDYntWA4jX2lcGKxDKRkjo2CEkXdxjVqUHGSfN36pveiAlb57w2BTuNc2CYaj1ByzjDAdmfs28L9nZmncpCvCVDZUJ/w38XMDPDEOfvZ8qcUIxUtEUrZSVR1tKKd8iqdVqTzeWI+FS1Eze1lhWPhknuQK0H/LWJHuM9+OGn9WVXao6QaWeNiG0HlG9U31L5z+cSS+bAjvsbjpj1cX+OfDkPLcRhEelYzvy59sJ6SU2QHVwL1AjZvrAvNyGvgnYgUmyMngYDJPRYQZLgck5sly3Hn40zWXu7gQKpGF93w8VwMBGDDnzqesr8Jv7lcgN/SUH/V+vnWGjxDTa9Y4UWP8gvi2LWSM1ySL1hHkmm0WbayzYdKqk4QpveqwCuPHfFSYG9SxavfcObTa8khwbLspDvYCS9nBz+v4lZiIIYi/BL1HUl6SLML7vq8jPE9bnfmoMvq6YOG3tv2QCqtuH550wUtDfTYlYyom2m9iG7qI2kDbm+1RSMXWloDTyKEeKhx+tt1waMTZC0CdfxB5EtHAcuvNLeJVyZXT2NGOkrhWAhIhL8Q4g3PbShjo3HKtPDMj3/KduWHv2Wg/dMdhjLMqMeEfeLn8uCmoIlNNTNNARub3UcA75vYot8D4Q5MKDZWMJ8z6CujJSNFZUDfzRqjF03DFXQ18KVw=
  app: bibliotheque-saucisson-10448
