language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  #PROD_DB_URI
  - secure: HmgNTy8otaWME8C2luai2oJuAoingiTr4vZeiexN8fa2N3Sj8S41AvX2yCqV8w+OE7HALMdYATqy52D7sR+irkV77OvvTUHbJGPz3ge2Xjn27huW/PyxKJsSP1UnFu1xLuzMUyzjLrO+qH+is6vcx8L1ETcQdtZvuTBfzV4JxPhg9khVxlaFbhXvftbiq3VLMO8jmUSftzH3Eu5FxmTv6gC33ZOlgnIH/MvOO+hYLAOfb3lH1SDxszciryMVL7VXOW2e7kQ2f+Vat+mRtDdW+eXELth/ixl9KWjYsujhAVaVDRUip4HPBhdQFpV6RUC+SbhoJve0vrv7qZcN4uJeTZwv+i25+Tz+S8GI9XjQU1yTEJLnrh53+qNffYBdJmn5TawklXYxMpWI5vVk1+RJ6cifdeFy77oBsoDnF9P/wOVybykVRc/oYex7K4qtywHcVeC3PJrYhQfelqQ1kEggplgRbvPRdf7+hW718AFSwpz/wuMpMCyekVbG3Nn9EwHgaB6IGGBOgl+zpROJG+1ENhzx3PjKahrJwOFU4BbFgN4Oo0Ll44TKEI6CzORhMvw8L1wyoKh5gxRfa1elKJjtdajrfJaD27IqYvuR8mofZtvLjGmimCwvvFIpMQ+jooCqpMxxAhZ4c192aelmUL4MPJ60oXllx5N3JIy2dmVKDlA=
  #TEST_DB
  - secure: aEt5xZoD+odHBpqJVsMEF7NJKw82VhdswAThwvBZHsaPWvzmr+1/6PcsqZOwzWgDxW+MDzLmAfevR6byF6e2atjO8Im937Ye7BEqATYn8hXmrezpjQ9dXRHLnS9l3WTZnTIFQ1NEAFe0S/gb33AItUeGdCf10ZrAsQNjLGKXVOlIyQ6NuZO72u1iJ1VqnN1wv17d7IdCf0rmWuG03cZlIOLdBI1DyVbsy9EoQwibVXb3F/K0ez0yuGfVMU/mKJ5+Drxu2F/z2ywXpT2RNPyO/cDyRI8jJwDw6dz0cCZgJg62koJ/T/IytI+PPcgsu9AaSzzJoQXXvJ6Om9oVI6dRCT0zIAT4jaLVHG64dV9oG1aLeCaJcbBTJXE5/HbB2JjqE1+wG5UjZwKuwwbT7elWsQj5egS6KHymT8ZpvTI7JglkSTJU7h3dl1hUpCVSZUF2vLlovTtQEkYmzByUehcyC/KDOe5uG+9gFvqGbLqr6qn1ZCL+sO4PWvSxHYP8bpGzPGOlAggFW9EaE5j97WwLIOi7lNhN8S+DrTqMOCBTFRfTLUhxoGkCTPSD333MSFLNcKmvjhXf2p0KIK1izq1SzIGI6RIzRFC2v5lr9uPmRM9PzAgtVf7l1t8cO2XzSokdZrDIv6kj7a8LYPhmGNLDjbU+mHVel1pB8bdDwvx32dk=
  #JWTSECRET
  - secure: RfcwntTnNFHuXegombPPGdRVkBySSiRF7DLkCfNQdaOHdiUyuEiTKTT8LA+AQsy7aYH41ZjF1CsMbAZS5GXwHIUpzcwM4I25YxVReJ0e2gcdzmNbDuv5LfFLgf6penVqa94ADLLkem23KP37qM/5+/wCJH1EcFbGOebQAZXjpu2I77bHNrMgO/MZo+lPYzEa57xAjc1YYG/j5V5TJeqVzLp8jqrluM3vBMTG9UXCsAlIAav58dDaEA23YYd9LBXxumr1SdrwQX/78xu13aIX+qaGoBdKubH40B5F+RR94ujHaDoVE5B8/eyROcMrNzPI+Telhu/JyESeZbyTkei6h8OtVQKiOEJpQjogYcfcVI0ChCE3ir0IQTAISJP2d1+iC/JX+MpgZt1SeK78rqvC1OEpWA6q9R54X/ddJ/+ck3NeJvisp1RdhkP58KNXZN03pnEousvcIN1BwrLj7xCjmYP2BiShwDgeYmtiY/FVxQ2lFlOdn/dBhe0QO3ZbcEOlm2s7SchHuimckfn5L1E/hoscrtfjHLvjKWnIbxcsGd+cBJ/aBoeAlE+uOLdC7M2K32BzEVxbL9pLQD+AslByqF+v+pxxFpJpgwsOPqLcs4TcbB/f56KTluKvooXgG89G3r0AupWyCRnuvOGAcX553sFmHNqxrRjaYOeZW1lwt/Q=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
services:
- postgresql
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: m//KYCzxk6b9i5MuELc4YRQg3fgE1qf7dT3OJu2yXdVMYdbNDxoMBDFZJeEAq+RSO660iD2peeJAs41rdZFvbRQzmGJ6qJErJbmm5n6+4Im8H2o96qnMVcAw9k4OSUJVh1D/2CZqO+pHPgORhA/anyIqJ0lRPQr7TKEXa3ppX5F+ychFchbuLBzqOnbykB3GO9cv7WhtJHqP14t2EWUKPsMbJV/HHIu401LtabbVdSSGhGTzIQ/M6DvE6cNCkCAi0fk730n/0I2qUOJpnSZlMxfJexYo3tHURWe5rcfiyUXSVyXRuR7rJBfVs2AOpWaEMxfe4N/Fxxm087wNlT4mZkfAC4+czj78naZEDhpPlNHWuOIZ/z7wEz0TXAjsn3EELXaYgg33bm7URPlywx+RtFfbW1hT/SRxdf9rDMDUKVOd62+vUz9/yPmYlRN3BCOdW/NOuD44rqKVEJpuW1OltObsct/N/nbz9jsdxPyi5JVqQzsvsIGGfI9ZO5mGebFhrZfSY7H68F/o3AYz7ANF2FClwYotRcJRuUiM+VtO1RMqspUGFurrJ2Y40+rCzxQlnxIZVFszKwzJNTmFQXIbXW8WtnT5p3pO986kWaQe5SUvvtn8yllHxSH065mOctsxdJ1a7ZVqjPxHp+u9/gYTYnmFPuvJgnvs3Kjcyz47RFs=
  app: daily-checkup-staging
