language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  # - secure: vU/ApAiYZMV3lPxGzgCiuUl5q/1eW0ivpP0R0JYjQ/mOk0eGVo48u5vBqYq066QQdkVbxjfenYWQOpE0z6luBwOiMFFm+bvI3glxVL1jp+W0ruc4CyN4O1jc1C/EWxsngBUbHRJGWr6yX/wmu7fBJE7DRpyq1Mb0YebMYbNpf0rlaYZsWGL+V03bClZe49Qbkciea4CWHRIn8x9EBeGoNIFNmF5l+Ec1Y42NpQ7x7oUSBzZ+++ai8hWBUXMnywh68j2CB5N6Px3RCjp2lG/VDlUUZ34yh7rHiD5ppidV3Qj4116/RPrWDPIah5maGTsoBq36tkrlsYaDE/xODO4Gp0m4I1vs5i9BxoL2gWo61k3QKR6haE2vvjzYRoV81V9xLfSbpRHn+mzfQ1M9sDLrWG71K4SRRg0PK+UodR7++zUyHtKZtx55nGV7ae+N+cj4sgvHD7W84SKdhtKSdNu7bHVwx+im0QQJSwphQ0N8eDnnkLXw6qnKQLcXToDxkwWO/riQZ8KOjj1Q7i/penhIRBT+JPYvJsQ9Ftl8JL7xhvwF1ZLwW4nMyCJyntF1PNeu8Ry9T9Fi/IqTJjhbM9MAWbWyIc8ScOIFEt5/tR+Odxv+714c9ERAjlF/ulo6gdCEq3j8j7YUzaazl2a/XgsvmJZR7mIbLJMUbKsOwOYbAGg=
  # - secure: ueqfcXd65Kia6E/fDi0BVWVMs5Prw0mxWDpGmFb88qnie1jobhVw4Ozvw7Eimf6UOLRsyqCFdUcp16sLN6E4BjLZCPiRBTU+P8FgKkznnTR8YbNUoBzRMRSdCOsKRsc0/fx1DRlrC53DbNXAbnzqu2VJPaKooTpQ7PA/G7raN4LtErgg4QD2k/WKaRBlaHFbLf2dZ8f23skKj92EI4RSPgfr9Ahd9pX2pyojUe9zemLOPmB82GxP7NKxGQ46kbNPF2RfUJP7igR643Nb3y6R51jcLbBCzLcN3G0AGTnTPzWGahxu8AG5JorEF/BE0zJQnNTOGkUkzcaewQYAmJd4DfxGTWlj5PEEzJNE60dcTnxO7SJX2xTsnBON3pEfCHBYiM0KbMkAUkAzayd6tsy22wOP0Sv/kKoxPYa6HYyNAp4/Cxa3z+iI9e6Ol9WnArrGuQ4QfolkNag9nLhUxPU0mEIpp2ILOXcroQdHXQcs5GA36ideous6bCqnD462nANynezAHFCFwu+Qmt4geVNcWjVQQzvbubMSdsXpcnYrC4930x/JoAdJr2tqHfjZ4qDNNiJlcB55+OtHCjwUHoUX76QbapPM33Z3/+47nPJZVBks0QRChkP+EFHoqXPoZSdNMrTaf9jKR4FLWwefBQPm9UosO4LSaS/H6pnjDwN4F08=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- postgresql
after_success: npm run coverage
