language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - secure: s6/R8v6Nxe8Vw0gnge+0/my7AHHEscWivpT9u847G/haqmULznNg3rCI3g6x2ws9JL7gcR4MsHH0giaxg1/qxT2qgvi3PiMd1Gwt8B7mfGIRm7nznAfU3KvsRpOlvTUdHzagldX1SfNvo5ouARI7EDALzkWiXik06eWArpQ0qlLr/zZWtVdlTmBaIWGseyB8dc2qkGgZNGmy3QqhwWX1IX5URqQ45EgtKcUuaWMFvmII4WpMIgqGMZ94HJPQ92Ubf4SULf8pZzNNS36L8Tf12XTr8rQcYnplz52W09O/Vydtwbz35xkuPnMTu1lRaUm/wUIbQxfVMLeHfkyPWk7H4nuGQTs5lk1se+3ZwpL3hN+dXYp0N4vnz0gfuxLRMSzuJcSgUwG7pndwdjA56o77ANpyS2POtOsSySfkKBEmFNbAGD1juVbOFmACbNz7pBDaGg1xjrqmvRLnIkLhN6uthSUtUDbIYoe3C4aygOnSSMFbe9Iet4cNiGfyNM8vtBitTiNtxY8F2hCkeEtiuYz353kj9VGkwaR482uep0CQzcdHlvzq1XLuXhDwwYK57x6ZcBOpHWWwjM7wOBnSVpL/OX9fhbn4HQpCy0m3Nw3K7WDdfqJr2wboPbn3mxxeH2rhUnHLQiNN8RG4eVbDXXGdSwbFoSk+f+cE+LVuAE5yx8w=
before_install:
  script:
    - export
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - postgresql
after_success: npm run coverage
