language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - secure: wGo965DMbDB5C0E1qyuhc+bm0xeZ/Q+cXviNs89051RpGvMktVS9vgnYyRMpnUn2P1MxaI2EppB2ZspetDrASOA5u4kHhYjExB8fdpqZ1TcIGDC5PXorA77Oy6HBsl/OwshKyVuSAOa9mJqaFEMKVKi228yyWGUWEi9VuItpRGvt6GFitd9sFL1lSxZa8d34Du8G2r/dc1PisBJ9a0uT7PdO6uc0dvOE0M33L/uFamHT6LbmA3buy2KgZzrfpMlBNSpMXD3WJdvr78q1hNyNmms/cE492sOxekBvi1gBJ5Rp9cDToChRkrmF/+LO8857t4cxileeDA8r5j9ojw4NcD7/KOkl6UMo9zojMbmsOfdBKllaAdJabXvOswpz6jfue7vJqlBfr+k1ocpVWRGyq2toVm4UiaK9jKvxlDRYees9v2Cx3nX7BptAlrgsg/q+SkwOqgITdPEgxx6Ax0ljOAKoA5D6kQnZThYLaND6xPtaQvPDjB5DmtHW5Ar18b2m3gN3CF1uAahc12aQySG1CBvbMKx6D7/50d7EnpEvxYRjqitaMYPKqVIz1IZULRyrdr8D2BzEU1chjSEC726fH9f6UzcL2jTq3le5QD2ehWuI5cZEV6F2TmRRniMrlxOOmsqjX1Cp4wX+b+VTKLJq0TBokOaf1obLKculbSSzKL8=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - postgresql
script:
  - echo $PROD_DB_URI
after_success: npm run coverage
