language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - PROD_DB_URI=postgres://BBSCorp:_chiaPower17@mymdquizdb.cwyegj8iv25h.us-west-1.rds.amazonaws.com/MD_Quiz_DB
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
services:
  - postgresql
after_success: npm run coverage
